data_config:
  train_file: train.jsonl
  val_file: test.jsonl
  test_file: test.jsonl
  num_proc: 1

combine: True
max_input_length: 512
max_output_length: 512

training_args:
  do_train: True
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: ./output
  max_steps: 3000
  bf16: true
  # fp16: false
  # needed to be fit for the dataset
  learning_rate: 5e-5
  # settings for data loading
  per_device_train_batch_size: 1
  dataloader_num_workers: 16
  remove_unused_columns: false
  # false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 500
  # settings for logging
  # logging_dir: ./output/ustc
  log_level: info
  logging_strategy: steps
  logging_steps: 100
  # settings for evaluation
  do_eval: False
  evaluation_strategy: no
  per_device_eval_batch_size: 1
  eval_strategy: steps
  eval_steps: 10
  # settings for optimizer
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 512
  # set your absolute deepspeed path here
  # deepspeed: configs/ds_zero_3.json
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["query_key_value"]
